### PR TITLE
[Improvement] Security-connected changes

### PR DESCRIPTION
**Pull request by maxmosk**

### CODE REVIEW

**Comment by nerett** [comment]
Screenshot_20220430_150511

**Comment by nerett** [comment]
That's because we use uninitialized `$should_open`, that is only created when proceeding with `-o` option

**Comment by sin-diesel** [comment]
Yes, please add  `should_open` variable initialisation.

**Comment by maxmosk** [comment]
> That's because we use uninitialized `$should_open`, that is only created when proceeding with `-o` option

Agree, fixed. But the most important error was with ```egrep``` and ```-e```. If task not found, it interrupt execution.

**Review by sin-diesel — APPROVED** [review]

**Pull request merged**
